name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php_version: [7.4, 8.1]
        laravel_version: [7.*, 8.*, 9.*]          
        exclude:
          - laravel_version: 9.*
            php_version: 7.4
          - laravel_version: 8.*
            php_version: 7.4
          - laravel_version: 7.*
            php_version: 8.1
            
    name: PHP ${{ matrix.php_version }} - Laravel ${{ matrix.laravel_version }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
          tools: composer:v1

      - name: Validate composer.json
        run: composer validate
      
      - name: Run composer install
        run: composer install --no-interaction --no-suggest
      
      - name: Install Laravel
        run: composer require "laravel/framework:${{ matrix.laravel_version }}" --no-interaction --no-update

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
